### ISSUE TITLE
BACDL_BIP

### ISSUE THREAD

**Issue by ossisyri** [kmtaylor/libbacnet#2]
Hello,

should Bacnet IP work with this packet?

There in a dlenv.c file:
`
# endif
# if defined(BACDL_BIP)
# if defined(BIP_DEBUG)

```
BIP_Debug = true;
```
# endif

```
pEnv = getenv("BACNET_IP_PORT");
if (pEnv) {
    bip_set_port(htons((uint16_t) strtol(pEnv, NULL, 0)));
} else {
```

`

BACDL_BIP is not defined and then IP left uninitialized.

There in http://bacnet.sourceforge.net/ is said to use 
`make BACDL_DEFINE=-DBACDL_MSTP=1 clean all`
to make MSTP possible.

I tried
`make BACDL_DEFINE=-DBACDL_BIP=1 clean all`
Without success.

If I give BACDL_BIP=1 as CFLAGS I get in trouble.
`make CFLAGS+=-DBACDL_BIP=1 clean all`

[biperror.txt](https://github.com/kmtaylor/libbacnet/files/316203/biperror.txt)

Is there somekind of bug or do I misuse something?

**Comment by kmtaylor** [comment]
Hi there,

Bacnet over IP should work without modification. Instead of passing environment variables to make, I've set up the same variables as --enable/disable options in the configure script. But you shouldn't need to use these if you want Bacnet/IP.

The build scripts provided here haven't been updated to keep track with changes that are happening upstream. If you don't mind using an older version of the stack, the build scripts will work well with release r2895.

The process should work with something like the following:
svn checkout -r2895 https://svn.code.sf.net/p/bacnet/code/trunk/bacnet-stack
cd bacnet-stack
git clone https://github.com/kmtaylor/libbacnet.git
patch -p0 < libbacnet/patches/datalink.patch
cd libbacnet
./bootstrap.sh
./configure
make
make install
